### ISSUE TITLE
use deep_Q_learner.py to train agent in Atari occured error

### ISSUE THREAD

**Issue by fangchuan** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#16]
today i use the code in ch6 deep_Q_learner.py to train agent in Atari, as the instruction of the book, but i faced up some problems when i run the following command:
     `python deep_Q_learner.py --env RiverrideNoFrameskip-v4`
and the error information:
`
Traceback (most recent call last):
  File "deep_Q_learner.py", line 287, in <module>
    agent.replay_experience()
  File "deep_Q_learner.py", line 170, in replay_experience
    self.learn_from_batch_experience(experience_batch)
  File "deep_Q_learner.py", line 151, in learn_from_batch_experience
    self.Q_target(next_obs_batch).max(1)[0].data
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray`

I'm not familiar with pytorch, it seems to be relative with the version of pytorch. the torch i installed in the virtualenv is 1.0 (by `pip install torch torchvision` ).  However, i run the Shallow_Q_Learner.py introduced by the book successfully. Is there anybody can help me locate and solve the error? thanks!

**Comment by praveen-palanisamy** [comment]
Hi @fangchuan 
Yes. I can help you locate & solve the error.

Thank you for reporting the issue. As you guessed, it is because of changes in PyTorch v 1.0 ([similar issue on SO](https://stackoverflow.com/questions/53938977/typeerror-add-argument-other-position-1-must-be-tensor-not-numpy-ndarra)) and the error comes up when used with a cuda device. 

I have pushed changes that should fix the issue when using the latest PyTorch (1.0.1.post2). It also will work with the the version (0.4.1) as per the [conda_env.yaml](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/conda_env.yaml) in this repo.

Please pull/update your fork to get the changes and re-open in case you still face this issue. We will fix it.

As a side note, in the command you tried to run: `python deep_Q_learner.py --env RiverrideNoFrameskip-v4` there is a typo. The Atari environment name is River**raid**NoFrameskip-v4 and not River**ride**NoFrameskip-v4. But I guess this was just a typo in your issue description because you would have got an error regarding the name otherwise.

**Comment by fangchuan** [comment]
thanks for your help, @praveen-palanisamy , it works!
