### ISSUE TITLE
different scene after the call of reset_env()

### ISSUE THREAD

**Issue by fangchuan** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#21]
hi, recently I have done many improvement to my agent and the carla_env,  today I want to replace the `env.reset()` function with the `env.reset_env()` function in the loop of my training process, because each time the `env.reset()` needs to kill and sweep old carla server process , then create a new carla serve process. It's too time-consuming and occupy most percentage of CPU during the step. 
So, I replace the `env.reset()` function with the `env.reset_env()` function, however, something unexpected happened. When I reset the carla environment first time, it shows me **the first scene**  as the below picture. Next time I after reset_env, (it doesnot kill the process), it show me **second scene** as the below picture, then each time I call the reset_env(), the scene is always the  **second scene**。 I'm sure it is in the Town01. I have reviewed the code in `carla_env.py`, and I didnot find the cause of this problem.

**Comment by ryanwang522** [comment]
I have similar question in #20

**Comment by fangchuan** [comment]
![Town01_first_scene](https://user-images.githubusercontent.com/8519718/54760172-7febad80-4c2a-11e9-98cb-574bb97eaa46.png)
![Town01_second_scene](https://user-images.githubusercontent.com/8519718/54760180-811cda80-4c2a-11e9-96a0-5dd2ff185efd.png)

**Comment by fangchuan** [comment]
Although the different scenes donot affect my training process, but I find it's wired because I cannot find what makes this problem, maybe the carla's problem? I am looking forward to your help. @praveen-palanisamy

**Comment by praveen-palanisamy** [comment]
@fangchuan: Good job on discovering a bug in Carla (0.8.x) :)
As you have note, on the first reset (episode), a different (incorrect) scene is generated but from the second reset (episode) onward, the correct scene is rendered. This happens because of a bug in the Carla server which causes the server to return the list of map node items in a reversed order.

Visually this is easier to see. On the first `reset()` the node IDs on the map are as shown below:
![first-ep-node-order](https://user-images.githubusercontent.com/4332953/38862776-1ccf45e4-4236-11e8-82dd-d238611c9e94.png)

But from the second call to `reset()` and thereafter, the node IDs are returned in correct order as shown below:
![second-ep-node-order](https://user-images.githubusercontent.com/4332953/38862789-28b66f0e-4236-11e8-9837-2077a229efaa.png)
(Notice how the location of the node locations 1, 2,... change in the above two figures)

This, as you also note, doesn't affect the learning performance of the agent much. This affects the start-state distribution which is often times better for the agent and helps in generalization. 

If you absolutely want to not have such a behavior, I can think of one workaround at the moment with Carla 0.8.x: For the first time after the server process is spawned, perform two resets (instead of the usual one). After that, the training can go on as usual until the next time a new carla server process is created.

**Comment by fangchuan** [comment]
@

**Comment by fangchuan** [comment]
This solution doesn't work, and I reviewed the `reset_env()` again, I cannot figure out this problem, could you help me? @praveen-palanisamy , I really need to control my memory in my limited computer, otherwise it would affect my training process.
