### ISSUE TITLE
Have you tried to use DQN on the Carla environment?

### ISSUE THREAD

**Issue by Derekabc** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#26]
I see you have DQN network on Chapter 6 and Carla environment on Chapter 8. Do you tried to train DQN on Carla env and how about the performance?

**Comment by praveen-palanisamy** [comment]
Yes. The DQN in chapter 6 ( which is actually a n-step double DQN) on an average required a minimum of 10M frames to converge to a good Q-function and therefore a reasonable driving policy.

You can set  `"discrete_actions": True` in the `ENV_CONFIG` and then use the DQN agent from Chapter 6 to train an agent in the CARLA environment.

**Comment by Derekabc** [comment]
Thank you for your reply. I made some changes on the code and I wonder how to choose the size of replay buffer based on Carla simluator environment.  I see that you choose 1e6, but this size is so large for the model to fill the pool.

**Comment by praveen-palanisamy** [comment]
@Derekabc: For deep RL and especially with DQN, the number of samples required to train a reasonably good policy in a complex environment like the driving environment, is large. A replay memory with a capacity of 1e6 for such an environment is reasonable if not a bare minimum.

Closing this item since there weren't any update. Feel free to re-open or create a new item if you need more info.
