### ISSUE TITLE
Question about A3C (ch8)

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#6]
Hi, 

I have a question about the plots presented in `Ch8`, in the section of **"Training and testing the deep n-step advantage actor-critic agent"** in the book.

The Tensorbroad plots in this section present three graphs for `actor0/actor_loss`, `actor0/critic_loss`, and `actor0/ep_reward`. My question is what does x-axis present? I assume it is the number of frames. If so, it shows for a simple `pendulum-v0` it takes roughly 3M frame to get some results? Am I right? I aware the A3C are not sample efficient, but I think this number is kinda unreasonable?

**Comment by praveen-palanisamy** [comment]
The x-axis is the number of steps. But the plots you are referring to are for an n-step actor-critic agent (single actor) and not A3C. The large number of steps is probably because it is a continuous control task from pixels which is relatively harder and also there was only one actor in that experiment. The aim of that section is to show how varying the `n` in n-step learning affects the performance of the Actor-Critic agent so, it was not necessarily optimized for better sample efficiency. It can definitely be improved. 
Also, the Gym `Pendulum-v0` environment does not define a "solved" condition so, mean ep_reward in the range ~-200 to -130 is as good as it can get.

In CARLA with simpler scenarios like lane keeping and slight turns, the agent learns a reasonably good policy in about ~7M steps.

**Comment by AliBaheri** [comment]
Thanks for your clear response. I still have a couple of questions. Sorry if they seems kinda trivial:

1) I want to to see how the car drives using that per-trained model available in the repo. However running the following command the car drives crazy with negative reward:

`python a2c_agent.py --env Carla-v0 --test`

Do you remenber how long it takes (i.e., how many steps) for a fairly good driving behavior? What I see from this command is just several negative reward.

2) Following you previous answer, what do you mean by **step**? Dose step mean the **number of episode** or **number of frames**? Number of _time_ step dose not make much sense in this context for me.

Thanks for your time.

**Comment by praveen-palanisamy** [comment]
1. The reason why the car is driving crazy with negative rewards is because the policy is not a trained policy. The `--test` argument to the `a2c_agent.py` script will load a trained policy **if available**. If not, the script will notify that the agent will be trained from scratch and it will prompt you for a key input as per these lines:
https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/34adb43a9d419e0de5472b268fe6102debccded6/ch8/a2c_agent.py#L295-L297
 
So, probably you didn't train (and save) the agent in the `Carla-v0` environment. I did not upload the trained policy for the `Carla-v0` environment to keep the repository size small. 
For a good driving behavior in the `Carla-v0` environment, the A2C agent took about ~5M to 7M steps.

2. The **steps** refers to the number of interactions with the environment. Roughly, it is the number of times `env.step(...)` is called. An **episode** can last for several steps and until the agent's action results in a terminal environment state. The **number of frames** refers to the number of observations (image frames) received by the agent from the environment. Sometimes (for example, when using Frame-stacking) the number of frames can be much larger than the number of steps.

You can find the available pre-trained agent "brains" with some notes about them in the [trained_models](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch8/trained_models) directory.

**Comment by AliBaheri** [comment]
Thanks for your response.

ohh, I see. In fact I had run another code where somewhere else where there was a pre-trained model and for some reason I thought that there exist a pre-trained model in this repo as well... So

**Comment by praveen-palanisamy** [comment]
I trained the [a2c_agent](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/a2c_agent.py) for a few hours on the `Carla-v0` environment and pushed the trained model to the repo. I also updated the [trained_models README](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch8/trained_models) with a sample command for running the agent with the trained policy. Hope that helps.

**Comment by AliBaheri** [comment]
Thanks Praveen,
I have run the trained model, but I cannot see a good driving behavior. Are you able to see that car drives *fairly* smooth?

**Comment by AliBaheri** [comment]
I have also had a general question. What kind of GPUs you recommend for such a high-fidelity environment? Is it better to run on cloud such as AWS or etc. or a local GPU such as NVIDIA GTX?
Thanks for your advice.

Best,

**Comment by praveen-palanisamy** [comment]
**Regarding the trained model**: Yes. With the trained model, the agent drives the car almost always to the goal. It does not depart from its lane and so does lane keeping quite well. Note that the environment will reset once the car reaches the goal.

**Regarding AWS vs local GPU:**  In general, during the initial phases of your development, where you would like to be able to customize/ develop/ debug iteratively and faster, you might benefit from having a local machine with decent number of CPU cores (4/8/16) and 1 NVIDIA GPU (GTX 1080 is economical). Once you have a mature implementation / experiment that you would like to train, which will benefit from having more number of CPU cores (and GPUs) and typically involve little or no interaction, you can leverage AWS to do the training to speed up the process. Once trained, you can transfer the trained models and the logs to your local computer for further analysis and improvements.

**Comment by AliBaheri** [comment]
Thanks. It is interesting that you see a fairly good driving behavior. Because when I follow the logs in `tensorboard` I see several negative rewards most of the time after finishing each episode. May be I miss something here and comes from my fault.

**Comment by AliBaheri** [comment]
Thanks. It is interesting that you see a fairly good driving behavior. Because when I follow the logs in Tensorboard I see several negative rewards most of the time after finishing each episode. May be I miss something here. Dose you agent able to turn right or left before ending an episode?

**Comment by AliBaheri** [comment]
Thanks. It is interesting that you see a fairly good driving behavior. To me, when I follow the logs in `Tensorboard` I see several negative rewards most of the time after finishing each episode. May be I miss something here. Dose you agent able to turn right or left before ending an episode?

Even for simple Pendulum-v0 the reward is always negative from the pre-trained model. I assume that running the following command should give the results:
python a2c_agent.py --test --render --env Pendulum-v0

Am I right?

**Comment by AliBaheri** [comment]
Apologize for more questions here....

Is `a2c_agent.py` is there anything should be commented out if I want to run on AWS? I am asking this question because there are several `torch.device("cpu")` in the code and I am surprised when I initiate a powerful instances on AWS the outcome is even slower than my local PC?!! Would you please confirm this.

Thanks.

**Comment by praveen-palanisamy** [comment]
The reward with the trained policy should be +ve in the Carla-v0 environment most of the time. The reward reflects more-or-less the distance traveled without any infractions. 
The default Carla-v0 environment uses the Lane Keep scenario as per this line:
https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/df9ab3984237b3a02998e2c3d3df482f557945f9/ch8/environment/carla_gym/envs/carla_env.py#L75
So the environment will terminate the episode once the agent reaches the goal position (which likely is before the turn you are referring to). You can use another scenario based on the scenario definitions in [scenarios.json](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/environment/carla_gym/envs/scenarios.json) and set the start and goal positions accordingly.

For the `Pendulum-v0` environment, (like I mentioned in one of the previous comments above), the best mean episode reward obtainable is about **-130** (notice the negative sign) as per the OpenAI benchmarks. The trained a2c_agent policy in this repo achieves mean episode reward in the range ~-200 to -130 (still negative). So, it is normal to always negative rewards. The magnitude and sign really depends on the environment implementation. It will be worthwhile to look at the agent's performance visually (using the `--render` flag) to judge. The command you used should work as long as the `trained_models` directory has the trained model file for that environment.

**Comment by praveen-palanisamy** [comment]
The use of GPU (cuda) vs CPU for the agent training is determined based on the user configuration and the available hardware. The device selection code for training is in the following lines:
https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/df9ab3984237b3a02998e2c3d3df482f557945f9/ch8/a2c_agent.py#L54-L56

The other `torch.device("cpu")` calls in the code are for inference (only forward passes) and retrieving the result to be used by other routines on the CPU. There shouldn't be a need to comment out any lines to run on AWS as the device selection is automatic based on the GPU availability and the configuration.
You can increase/decrease the number of parallel agents/workers using the [a2c_parameters.json](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/a2c_parameters.json) file. Note that each parallel instance will use 1 CPU core. It is advisable to set the number of agents/workers to be less than or equal to the total number of available CPU cores.

Moreover, the Carla environment will run faster on a GPU so may be slow down on the AWS instance is because of some GPU driver misconfiguration that is preventing Carla to use the GPU? Carla can run on the CPU but at a very slow frame rate and is not suitable for training the agents (especially a2c and the async_a2c).  In my experiments, the agent training scales up with more CPU cores and GPU resources.

**Comment by AliBaheri** [comment]
Thanks for your clear response.

So I assume that the pre-trained model is just based on lane keeping in town2. So we should change the senator if we interested for turn or dynamic navigation. Would you please confirm my understanding?

**Comment by AliBaheri** [comment]
Thanks for clarification. 

So I assume the existing pre-trained model is just based on lane keeping on town 2. If one interested to other scenarios such as turn of dynamic navigation s/he should train a model from skratch. Could you please confirm my understanding?

**Comment by AliBaheri** [comment]
Update: I can confirm running the pre-trainded model in CARLA lead always a negative reward without much (or obsolete) difference between in training mode. I think something goes wrong here, may be from my side.

**Comment by AliBaheri** [comment]
One more things I notice is in `carla_env.py` line 72 the `discrete_actions": True`. 
This dose not make sense in A2C/A3C where in this algorithm the action space is **continuous**. If it changes to `discrete_actions": False` the following error arise:

`Process DeepActorCriticAgent-1:
Traceback (most recent call last):
  File "/home/baheri/anaconda3/envs/rl_gym_book/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/baheri/HOIAWOG/ch8/a2c_agent.py", line 292, in run
    self.load()
  File "/home/baheri/HOIAWOG/ch8/a2c_agent.py", line 228, in load
    self.actor.load_state_dict(agent_state["Actor"])
  File "/home/baheri/anaconda3/envs/rl_gym_book/lib/python3.5/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Actor:
	Missing key(s) in state_dict: "actor_mu.weight", "actor_mu.bias", "actor_sigma.weight", "actor_sigma.bias". 
	Unexpected key(s) in state_dict: "logits.weight", "logits.bias". 
Killing live carla processes set()`

Are you able to reproduce this error?

**Comment by praveen-palanisamy** [comment]
Yes. The agent needs to be trained in the appropriate scenarios. The trained model I uploaded was with a few hours of training for the lane keeping scenario. For other scenarios that you are interested in, you do not have to necessarily start training the agent from scratch. If you load that trained policy parameters and continue training on the new scenarios, it should learn good policies much faster.

**Comment by praveen-palanisamy** [comment]
Regarding your observations with the pre-trained model's rewards:
It sounds strange. I tried to reproduce your issue by doing a fresh clone of this repo and running the pre-trained agent in the `Carla-v0` environment. The agent was doing well and got positive episode rewards. Below is the log (notice the **ep_reward:** values):

```bash
(rl_gym_book) praveen@ubuntu:~$git clone https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym.git HOIAWOG
(rl_gym_book) praveen@ubuntu:~$cd HOIAWOG/ch8
(rl_gym_book) praveen@ubuntu:~/HOIAWOG/ch8$python a2c_agent.py --test --env Carla-v0
Loaded Advantage Actor-Critic model state from trained_models/A2C_Carla-v0.ptm  which fetched a best mean reward of: -0.08981079755592294  and an all time best reward of: 1.0340544147491457
Initializing new Carla server...
Start pos 36 ([0.0, 3.0]), end 40 ([0.0, 3.0])
Starting new episode...
actor0:Episode#:0 	 ep_reward:0.1716839284479617 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:1 	 ep_reward:0.08453281730562442 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:2 	 ep_reward:0.010737545788288097 	 mean_ep_rew:nan best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:3 	 ep_reward:0.4108916156768798 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:4 	 ep_reward:-0.26511604218006135 	 mean_ep_rew:nan best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:5 	 ep_reward:0.4659429662704467 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:6 	 ep_reward:0.023224772512912755 	 mean_ep_rew:nan best_ep_reward:1.0340544147491457
ERROR: tcpserver 19628 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
^CProcess DeepActorCriticAgent-1:
```

**Comment by praveen-palanisamy** [comment]
> One more things I notice is in carla_env.py line 72 the "discrete_actions": True.
This dose not make sense in A2C/A3C because in this algorithms the action space should be always continuous and not discrete. If it changes to "discrete_actions": False the following error arises...

It is not necessary to use continuous policies with A2C/A3C. The actor-critic policy gradient  methods in general do not have anything inherent in the algorithm that is specific to continuous action valued policies. That said, the agent implementation in this repo will automatically choose discrete/continuous action policies based on the environment's action space definitions. The `Carla-v0` environment implementation supports both discrete and continuous action spaces. You can set `"discrete_actions:False"` and train a continuous policy.

The error you got is because you were setting the `"discrete_actions:False"` when loading the pre-trained discrete policy.

**Comment by AliBaheri** [comment]
Interesting and strange.

This is my log after fresh clone (...Most of the time `ep_reward` is negative.)

`(rl_gym_book) baheri@aerodrome:~$ git clone https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym.git HOIAWOG
Cloning into 'HOIAWOG'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 1171 (delta 14), reused 35 (delta 9), pack-reused 1111
Receiving objects: 100% (1171/1171), 50.86 MiB | 11.13 MiB/s, done.
Resolving deltas: 100% (603/603), done.
(rl_gym_book) baheri@aerodrome:~$ cd HOIAWOG/ch8
(rl_gym_book) baheri@aerodrome:~/HOIAWOG/ch8$ python a2c_agent.py --test --env Carla-v0
Loaded Advantage Actor-Critic model state from trained_models/A2C_Carla-v0.ptm  which fetched a best mean reward of: -0.08981079755592294  and an all time best reward of: 1.0340544147491457
Initializing new Carla server...
Start pos 36 ([0.0, 3.0]), end 40 ([0.0, 3.0])
Starting new episode...
/home/baheri/anaconda3/envs/rl_gym_book/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/baheri/anaconda3/envs/rl_gym_book/lib/python3.5/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
actor0:Episode#:0 	 ep_reward:-1.7531265632949773 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:1 	 ep_reward:-1.4002031571388247 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:2 	 ep_reward:0.10657712336778637 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:3 	 ep_reward:0.45455242328643786 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:4 	 ep_reward:-1.4253997046089173 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:5 	 ep_reward:-1.691057421984672 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:6 	 ep_reward:-1.757420496565104 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:7 	 ep_reward:0.24768941036224357 	 mean_ep_rew:nan	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 38835 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
`

**Comment by praveen-palanisamy** [comment]
Hmmm. One thing than can cause this strange behavior is if you are using a different version of CARLA server. (I trained the model using `0.8.2`). Ideally it shouldn't matter much because the agent just relies on the rendered driving scene but some other calculations (like the reward) may be different. It's good to check that to be sure.

**Comment by AliBaheri** [comment]
No. Actually based the CARLA authors, I use the stable version (`0.8.2`)...Really strange for different results,

**Comment by praveen-palanisamy** [comment]
Yeah. Strange. Few other things to check:
- Python package version changes if any (especially PyTorch). (I used the environment created using the [conda_env.yaml file](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/conda_env.yaml))
- CARLA logs to check to see if it is running without any issues at the default set frame-rate. 

Do you run CARLA with or without a GPU?

**Comment by AliBaheri** [comment]
-`python -c "import torch; print(torch.__version__)"`:

`0.4.1`

 I do not use external GPU. Furthermore, I followed instruction in the book and do not remember about `conda_env.yaml file`. By the way what is CARLA logs and how/where can I check it?

**Comment by AliBaheri** [comment]
Update: I can confirm other than CARLA, the pre-trained models works reasonably well for `Atari` and `BipedalWalker-v2`. Still confused why CARLA dose not work.

**Comment by AliBaheri** [comment]
>     * CARLA logs to check to see if it is running without any issues at the default set frame-rate.
> 
> 
It is not clear. What do you mean by issues?

**Comment by praveen-palanisamy** [comment]
The PyTorch version you reported to be using is recent enough. So I guess no issues with that. 

Now the only different I can think of that can contribute to this strange behavior is the observations coming from the the Carla-v0 environment. The stdout and stderr messages that are printed to console when CARLA is ran is usually pretty verbose. Checking that log to see if there are any obvious reported errors is what I suggested earlier. You can do that by running CARLA in isolation as the stdout is redirected when used with the Carla-v0 environment (you can change that if you want to print out to the console).

I should mention this though: I run the agent in test mode on a machine with a dedicated GPU. I do not get good frame-rates when running CARLA on the CPU.

Sorry that I have no other clue for why you are observing the strange behavior.

**Comment by githubce** [comment]
Solution provided by the author. You can reopen the issue if you want to continue discussion.
