### ISSUE TITLE
Question about ch7

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#8]
Hi Praveen, 
I have a basic question about the **Ch7.** I am interested to collect some observations and actions in CARLA similar to the gym environment. To achieve that goal, one can use the following simple code. But running this leads to following error:

` File "environment/carla_gym/envs/carla_env.py", line 326, in step_env`
    `action = DISCRETE_ACTIONS[int(action)]`
`TypeError: only size-1 arrays can be converted to Python scalars` 

```python
from environment import carla_gym
env = gym.make("Carla-v0")
def pick_random_action(t, current_action):
#     a = env.action_space.sample()
#     return a
    if t < 60:
        return np.array([0,1,0])
    
    if t % 5 > 0:
        return current_action

    rn = random.randint(0,9)
    if rn in [0]:
        return np.array([0,0,0])
    if rn in [1,2,3,4]:
        return np.array([0,1,0])
    if rn in [5,6,7]:
        return np.array([-1,0,0])
    if rn in [8]:
        return np.array([1,0,0])
    if rn in [9]:
        return np.array([0,0,1])



action = np.array([0,1,0])
for i_episode in range(500):
    print('-----')
    observation = env.reset()
    #env.render()
    t = 0
    done = False
    obs_sequence = []
    action_sequence = []
    while t < 300:
        t = t + 1
        action = pick_random_action(t, action)
        
        observation = observation.astype('float32') / 255.
              
        obs_sequence.append(observation)
        action_sequence.append(action)
        
        observation, reward, done, info = env.step(action)
    
    obs_data.append(obs_sequence)
    action_data.append(action_sequence)
    
    print("Episode {} finished after {} timesteps".format(i_episode, t+1))
    print("Dataset contains {} observations".format(sum(map(len, obs_data))))


```

Do you know how can I fix it?

**Comment by praveen-palanisamy** [comment]
Hi Ali,

The error is because in your code snipped, `action` is a 3 dimensional array instead of an integer.
As documented [here](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7#21-state-space-and-action-space-definitions) , when `"discrete_actions"` is set to true (the default), the action space of the `Carla-v0` environment is `Discrete(9)`.

Therefore, you can simplify your pick action function something like below:

```python
def pick_random_discrete_action(t, current_action):
#     a = env.action_space.sample()
#     return a
    if t < 60:
        return np.array(3)  # Go forward
    
    if t % 5 > 0:
        return current_action

    rn = random.randint(0,9)
   return rn
```
To see what each discrete action means, please refer to the table [here](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7#21-state-space-and-action-space-definitions).

If you want to use the continuous action space, you can set the `"discrete_actions": False` here:
https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/df9ab3984237b3a02998e2c3d3df482f557945f9/ch7/carla-gym/carla_gym/envs/carla_env.py#L70-L72

and then provide a 2 dimensional action (example: np.array([0, 1]) ) to the `env.step(...)` function. The definitions for the continuous action space is listed [here](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7#continuous-actions).

Hope that helps.

**Comment by AliBaheri** [comment]
Hi Praveen,

Do you have some thoughts for the last tread? 
Thanks.

**Comment by praveen-palanisamy** [comment]
@AliBaheri: Is your question answered?

**Comment by githubce** [comment]
Author provided the solution. Reopen if you want to continue discussion.
